InitializeSign,
2.0.7,
cosplay-pk.com,
https://play.google.com/store/apps/details?id=com.CPKStudio.CosplayPK3,
itms-services://?action=download-manifest&url=https://gitee.com/shenzhen_and_hebei/plistsave/raw/master/cpk.plist,
